<?php
defined('ENVIRONMENT') OR die('Invalid access');
themeFunctions::includeAddon('scroll-into-view-if-needed');
themeFunctions::includeAddon('polyfill');
themeFunctions::includeAddon('material-design-icons');
themeFunctions::includeAddon('vue');
themeFunctions::includeAddon('vuetify');
themeFunctions::includeAddon('vue-datepicker');
themeFunctions::includeAddon('vue-router');
themeFunctions::includeAddon('axios');
themeFunctions::includeAddon('font-awesome');
themeFunctions::includeAddon('google-tag-manager');
// themeFunctions::includeAddon('jquery');
// themeFunctions::includeAddon('tooltip');
// themeFunctions::includeAddon('bootstrap');
// themeFunctions::includeAddon('jquery-ui');
// themeFunctions::includeAddon('font-icons');
// themeFunctions::includeAddon('backstretch');
// themeFunctions::includeAddon('google-tag-manager');
// themeFunctions::includeAddon('custom/frontend');
// themeFunctions::includeAddon('facebook');
// themeFunctions::includeAddon('schema-org');
// themeFunctions::addIncludePath('includes/body/content_before.php', __DIR__ . '/top.php');
// themeFunctions::addIncludePath('includes/body/content_before.php', __DIR__ . '/menu.php');
themeFunctions::addIncludePath('includes/body/content.php', __DIR__ . '/content.php');
themeFunctions::addIncludePath('includes/body/content_after.php', __DIR__ . '/footer.php');
themeFunctions::addIncludePath('includes/head/stylesheets.php', __DIR__ . '/stylesheets.php');
themeFunctions::addIncludePath('includes/body/scripts.php', __DIR__ . '/scripts.php');
themeFunctions::loadLang('frontend');
themeFunctions::loadModule('cms/page',__DIR__ . '/content.php');
$this->content();