<?php
$config['menu_routes_permissions'] = array(
  array(
    'icon' => '<i class="fa fa-list"></i>',
    'title' => 'Rezervari',
    'route' => 'backend/trip/orders',
    'items' => array(),
  ),
  array(
    'icon' => '<i class="fa fa fa-users"></i>',
    'title' => 'Clienți',
    'route' => 'backend/accounts/customer',
    'items' => array(),
  ),
  array(
    'icon' => '<i class="fa fa-list-alt"></i>',
    'title' => 'Ticketing',
    'route' => 'backend/ticketing',
    'items' => array(),
  ),
  array(
    'icon' => '<i class="icon-presentation"></i>',
    'title' => 'Administrare site',
    'items' => array(),
  ),
  array(
    'icon' => '<i class="fa fa-users"></i>',
    'title' => 'Utilizatori',
    'items' => array(),
  ),
  'backend/trip/orders' => '',
  'backend/accounts/customer' => '',
  'backend/ticketing' => '',
  'backend/static/advantages' => '',
  'backend/sliders/homepage' => '',
  'backend/sliders/homebackground' => '',
  'backend/trip/packages' => '',
  'backend/offers/recommended' => '',
  'backend/offers/weekend' => '',
  'backend/offers/popular' => '',
  'backend/offers/holiday' => '',
  'backend/trip/flight_info' => '',
  'backend/trip/flights_settings' => '',
  'backend/trip/citybreak_settings' => '',
  'backend/cms/layouts' => '',
  'backend/payment_methods/agency' => '',
  'backend/payment_methods/bank' => '',
  'backend/payment_methods/online' => '',
  'backend/payment_gateways/payu' => '',
  'backend/trip/settings' => '',
  'backend/plugins/google/maps' => '',
  'backend/plugins/facebook/login' => '',
  'backend/accounts/admin' => '',
  'backend/accounts/roles' => '',
);